### PR TITLE
Allow placement override

### PR DESCRIPTION
**Pull request by danielpquinn**
How would you feel about letting users override the dynamic placement of each step? In my solution, a `placement` property is optionally added to each step configuration. If present and valid, the `placement` property is used to position the step regardless of whether or not the step fits into the browser window.

I updated the build, readme and example files, but I'm not sure if I should have updated the `example/nz-tour.js`. It looks like that file hadn't been updated in quite some time, which makes me think maybe you only update the examples when a new version is released or something.

Let me know what you think!

### CODE REVIEW

**Comment by tannerlinsley** [comment]
I would say that's a great idea. My only opinion is that it remains a
priority position if possible. No tooltip is useful off screen. I would
say, make it a priority option that accepts one string or an array of
strings as replacement priorities for the defaults. Then a secondary option
to disable the autofit completely. What do you think?

**Comment by danielpquinn** [comment]
I agree with your opinion, I'll see if I can come up with an elegant way to make that work :)

Great module, btw! (so much better than some of the alternatives out there)

**Comment by tannerlinsley** [comment]
Thanks! I appreciate the promotion and contribution!

**Comment by danielpquinn** [comment]
Okay, so I updated my PR with your suggestion and reverted my changes to the example file because I wasn't sure how to update the html that was generated from markdown. I also updated the readme and dist stuff. Let me know if you're cool with my placementPriority validation function - I had to reuse it for each step in `tour.steps`.

**Comment by danielpquinn** [comment]
🎷🎶

**Pull request merged**
