### PR TITLE
Fix package.json main attribute

### PR DESCRIPTION
**Pull request by lebolo**
`main` can no longer be an array (it must be a string in npm, but can be an array in bower)

See angular-ui/ui-grid#4743 as an example

### CODE REVIEW

**Comment by lebolo** [comment]
Thanks @tannerlinsley. Do you think you can deploy the latest versions to npm? npm still shows the latest as 1.0.0.

**Comment by tannerlinsley** [comment]
Would you be interested in helping me maintain the repo?

**Comment by lebolo** [comment]
:scream: Disclaimer: I've never maintained a repo before. But I would certainly be willing to help.

**Comment by tannerlinsley** [comment]
No better time to learn than now!  I'll add you as a collaborator both here and on npm, and you can start by doing your first npm release!  How does that sound?

**Comment by lebolo** [comment]
The adventure begins =) thanks

**Comment by davecranwell** [comment]
[ignore, wrong repo!]

**Comment by lebolo** [comment]
v1.1.0 released!

**Comment by tannerlinsley** [comment]
Luis ftw!

**Pull request merged**
